### ISSUE TITLE
afs-robotest setup/teardown: allow depmod to find libafs.ko/openafs.ko 

### ISSUE THREAD

**Issue by jhgorse** [openafs-contrib/openafs-robotest#12]
If we install/remove the kernel module, libafs.ko/openafs.ko, to and from this location
```
/lib/modules/$(uname -r)/kernel/fs/openafs/libafs.ko
```
Then run `depmod -a` after the change, the builtin linux kernel tools should work by default (on Debian-based systems).

**Comment by meffie** [comment]
Not sure I'm following your suggestion.

**Comment by jhgorse** [comment]
Add this `to afs-robotest setup` or perhaps, now that I think about it, `afsutil install` might be better place:
```
sudo mkdir -p /lib/modules/$(uname -r)/kernel/fs/openafs/
sudo cp libafs.ko /lib/modules/$(uname -r)/kernel/fs/openafs/libafs.ko
sudo depmod -a
```

Add this to `afsutil remove`:
```
sudo rm /lib/modules/$(uname -r)/kernel/fs/openafs/libafs.ko
```

I may hack afsutil tomorrow and give you a patch. The comment is mostly documentation. =)

**Comment by meffie** [comment]
Should be fixed in commit ca3b7d474e1b90fdf3dc34770b1036355f32110f.  Mark pointed out i was setting --enable-linux-kernel-packaging, not --with-linux-kernel-packaging.   (technically, this should have been an --enable option in openafs; too late to change it now.)

**Comment by jhgorse** [comment]
I believe this is separate. I think depmod is an indexer of linux kernel modules, so this is really about the afsutil install/remove. As soon as I get this spare linux box up and going, I should be able to test this and confirm.

**Comment by meffie** [comment]
We already use depmod -a when installing if built with linux packaging enabled, so I think this should fix the bug you were seeing.  See transarc.py.

**Comment by jhgorse** [comment]
Yep. It's all there. Thanks, Mike! You rock!
